### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by ctjessup** [Ritsuna/Foundry_FFD20#1]
I'm unable to get Foundry to see the FF content anywhere. I've manually copied and unzipped directly with no success. Is there something I'm missing or a step I'm not seeing? Any assistance would be greaty appreciated.

**Comment by 2014ALee** [comment]
I think ctjessup's problem is still going on

**Comment by Ritsuna** [comment]
hmmm, if you are using foundry, you should just be able to use https://raw.githubusercontent.com/Ritsuna/Foundry_FFD20/master/system.json to get the files, but at this point i recommend using the pre 8.x foundry version https://github.com/Ritsuna/Foundry_FFD20/releases/tag/0.1.16 as i am waiting on pf1e to update. could you please reach out to me on discord though the ffd20 discord group so that i can track down your problem?

**Comment by 2014ALee** [comment]
I used the raw.githubusercontent.com link and that seemed to work. I don't recall that link being available in the readme.md though.

**Comment by Ghozeil** [comment]
I can confirm https://raw.githubusercontent.com/Ritsuna/Foundry_FFD20/master/system.json into the manifest URL will download the system.
